export const CHANGE_FLOOR = 'CHANGE_FLOOR';
export const CHANGE_BUILDING = 'CHANGE_BUILDING';
export const CHANGE_CURRX = 'CHANGE_CURRX';
export const CHANGE_CURRY = 'CHANGE_CURRY';
export const CHANGE_SUMX = 'CHANGE_SUMX';
export const CHANGE_SUMY = 'CHANGE_SUMY';